runtime: java17
instance_class: F2

env_variables:
  SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL_PLACEHOLDER"
  SPRING_DATASOURCE_USERNAME: "SPRING_DATASOURCE_USERNAME_PLACEHOLDER"
  SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD_PLACEHOLDER"
  OAUTH2_CLIENT_ID: "OAUTH2_CLIENT_ID_PLACEHOLDER"
  OAUTH2_CLIENT_SECRET: "OAUTH2_CLIENT_SECRET_PLACEHOLDER"
  BRAINTREE_MERCHANT_ID: "BRAINTREE_MERCHANT_ID_PLACEHOLDER"
  BRAINTREE_PUBLIC_KEY: "BRAINTREE_PUBLIC_KEY_PLACEHOLDER"
  BRAINTREE_PRIVATE_KEY: "BRAINTREE_PRIVATE_KEY_PLACEHOLDER"
  OCR_API_KEY: "OCR_API_KEY_PLACEHOLDER"
  GROQ_API_KEY: "GROQ_API_KEY_PLACEHOLDER"
  MAIL_ID: "MAIL_ID_PLACEHOLDER"
  MAIL_PASSKEY: "MAIL_PASSKEY_PLACEHOLDER"
  SPRING_PROFILES_ACTIVE: "SPRING_PROFILES_ACTIVE_PLACEHOLDER"  # Placeholder to be replaced
  APP_SECURITY_SECRET_KEY: "passwordpassword"  # Encryption Config
  LOGGING_LEVEL_ROOT: "INFO"  # Logging
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "SPRING_DATASOURCE_DRIVER_CLASS_NAME_PLACEHOLDER"  # Placeholder for driver class name
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT_PLACEHOLDER"  # Placeholder for dialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: "SPRING_JPA_HIBERNATE_DDL_AUTO_PLACEHOLDER"  # Placeholder for ddl auto
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI"  # Placeholder for redirect URI
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE"  # Placeholder for scope
  SPRING_MAIL_HOST: "SPRING_MAIL_HOST_PLACEHOLDER"  # Placeholder for mail host
  SPRING_MAIL_PORT: "SPRING_MAIL_PORT_PLACEHOLDER"  # Placeholder for mail port
  SPRING_MAIL_USERNAME: "${MAIL_ID}"  # Mail Username
  SPRING_MAIL_PASSWORD: "${MAIL_PASSKEY}"  # Mail Password
  GROQ_API_URL: "https://api.groq.com/openai/v1/chat/completions"  # GROQ API URL
  OCR_API_URL: "https://api.ocr.space/parse/image"  # OCR API URL

