runtime: java17
instance_class: F2

env_variables:
  SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL_PLACEHOLDER"
  SPRING_DATASOURCE_USERNAME: "SPRING_DATASOURCE_USERNAME_PLACEHOLDER"
  SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD_PLACEHOLDER"
  OAUTH2_CLIENT_ID: "OAUTH2_CLIENT_ID_PLACEHOLDER"
  OAUTH2_CLIENT_SECRET: "OAUTH2_CLIENT_SECRET_PLACEHOLDER"
  BRAINTREE_MERCHANT_ID: "BRAINTREE_MERCHANT_ID_PLACEHOLDER"
  BRAINTREE_PUBLIC_KEY: "BRAINTREE_PUBLIC_KEY_PLACEHOLDER"
  BRAINTREE_PRIVATE_KEY: "BRAINTREE_PRIVATE_KEY_PLACEHOLDER"
  OCR_API_KEY: "OCR_API_KEY_PLACEHOLDER"
  GROQ_API_KEY: "GROQ_API_KEY_PLACEHOLDER"
  MAIL_ID: "MAIL_ID_PLACEHOLDER"
  MAIL_PASSKEY: "MAIL_PASSKEY_PLACEHOLDER"
  SPRING_PROFILES_ACTIVE: "dev"  # Default profile, can be overridden in CI/CD
  APP_SECURITY_SECRET_KEY: "passwordpassword"  # Encryption Config
  LOGGING_LEVEL_ROOT: "INFO"  # Logging
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"  # DB Config
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: "profile,email"  # Oauth2 Config
  SPRING_MAIL_HOST: "smtp.gmail.com"  # Mail Config
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "${MAIL_ID}"  # Added Mail Username
  SPRING_MAIL_PASSWORD: "${MAIL_PASSKEY}"  # Added Mail Password
  GROQ_API_URL: "https://api.groq.com/openai/v1/chat/completions"  # GROQ API URL
  OCR_API_URL: "https://api.ocr.space/parse/image"  # OCR API URL
