runtime: java17
instance_class: F2

env_variables:
  SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL_PLACEHOLDER"
  SPRING_DATASOURCE_USERNAME: "SPRING_DATASOURCE_USERNAME_PLACEHOLDER"
  SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD_PLACEHOLDER"
  OAUTH2_CLIENT_ID: "OAUTH2_CLIENT_ID_PLACEHOLDER"
  OAUTH2_CLIENT_SECRET: "OAUTH2_CLIENT_SECRET_PLACEHOLDER"
  BRAINTREE_MERCHANT_ID: "BRAINTREE_MERCHANT_ID_PLACEHOLDER"
  BRAINTREE_PUBLIC_KEY: "BRAINTREE_PUBLIC_KEY_PLACEHOLDER"
  BRAINTREE_PRIVATE_KEY: "BRAINTREE_PRIVATE_KEY_PLACEHOLDER"
  OCR_API_KEY: "OCR_API_KEY_PLACEHOLDER"
  GROQ_API_KEY: "GROQ_API_KEY_PLACEHOLDER"
  SPRING_MAIL_USERNAME: "MAIL_ID_PLACEHOLDER"
  SPRING_MAIL_PASSWORD: "MAIL_PASSKEY_PLACEHOLDER"
